# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class TestTest():
  def setup_method(self, method):
    self.driver = webdriver.Chrome()
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_test(self):
    self.driver.get("https://github.com/")
    self.driver.set_window_size(1033, 816)
    self.driver.find_element(By.CSS_SELECTOR, ".mr-2 > .octicon").click()
    element = self.driver.find_element(By.CSS_SELECTOR, ".mr-2 > .octicon")
    actions = ActionChains(self.driver)
    actions.move_to_element(element).perform()
    element = self.driver.find_element(By.CSS_SELECTOR, "body")
    actions = ActionChains(self.driver)
    actions.move_to_element(element, 0, 0).perform()
    self.driver.find_element(By.ID, "query-builder-test").click()
    self.driver.find_element(By.ID, "query-builder-test").send_keys("testing")
    self.driver.find_element(By.ID, "query-builder-test").send_keys(Keys.ENTER)
    self.driver.find_element(By.CSS_SELECTOR, "html").click()
  
